name: Publish on Tag

on:
  push:
    tags:
      - '*pre*'
      - '*rc*'
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [ 16.15.0 ]
    #     scope: ['@ballistagroup' ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: 16.15.0
          registry-url: 'https://registry.npmjs.org'
          scope: '@ballistagroup'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0
          mongodb-port: 37017
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          CI: true
      - run: npm run make-distribution
      - run: npm prune --production
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
